Fix #6 - Populating schedule_deviation and time_point values in database
CUTR-at-USF/ontime-performance-calculator pull request #16
Opened 2016-11-04 00:12 UTC by mohangandhiGH

Modified FeedProcessor.java to update schedule_deviation and timepoint values.
SELECT query is very fast now as oid column is made primary key. So, included '.... ORDER BY [oid] DESC 'in SELECT query.

2016-11-05 20:48 UTC, barbeau commented
A heads up that this branch now has conflicts you'll need to resolve.  So,  you will need to do the Git rebase I talked about in last meeting, rehashing sched_deviation on master.   See:
https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

2016-11-05 20:52 UTC, barbeau commented
I'd suggest checking out the Git UI within NetBeans,  IDEs make this a lot easier.  For example see:
https://blogs.oracle.com/geertjan/entry/git_in_netbeans_ide_7

2016-11-07 21:13 UTC, mohangandhiGH commented
@barbeau  I have rebased sched_deviation branch on top of master and pushed the modified changes to sched_deviation branch.  If everything seems good, we can merge this PR :).

2016-11-07 22:20 UTC, barbeau requested changes
@mohangandhiGH Thanks, this looks pretty good!  Two small changes requested in-line.  Feel free to make additional commits on top of this branch to fix individual details if that is easier - we can always squash via the Github PR tools.

2016-11-07 22:20 UTC, barbeau commented on src/main/java/edu/usf/cutr/OPC/FeedProcessor.java
> +                    Date timestampEST = new Date(timestampUT.getTime() + TimeZone.getTimeZone("EST").getRawOffset());
Instead of hard-coding this to `EST`, could you pull this from the GTFS `agency.txt` `agency_timezone` field instead?

2016-11-07 22:20 UTC, barbeau commented on src/main/java/edu/usf/cutr/OPC/FeedProcessor.java
> +		String sql = "SELECT TOP(10000) [oid], [timestamp], [trip_id], [position_latitude], [position_longitude]\n" +
Could you please remove the restriction on the `TOP(10000)` records here?  I'd like to be able to run the tool on all data that overlaps with the provided GTFS data (assuming we'll run this tool on non-HART datasets too).  I would suggest defaulting to running on all records, but also allow providing a command-line parameter to limit to the TOP X rows.

2016-11-08 14:51 UTC, merged

2016-11-08 14:52 UTC, barbeau commented
Looks good @mohangandhiGH, thanks!  I went ahead and merged this to get the master branch updated.  Could you also please add documentation on the new command line parameter for "number of records" to the README?

2016-11-09 02:21 UTC, mohangandhiGH commented
@barbeau I have added changes to README file in the PR #22 :)

2016-11-09 03:57 UTC, barbeau commented
Thanks @mohangandhiGH!